apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: py-artifactory-nov15-test-gitops-repository
spec:
  url: https://github.com/RHTAP-RHDH/py-artifactory-nov15-test-gitops